import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Box from "../components/Box";
import { Canvas, useFrame } from "@react-three/fiber";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/springanim">
        <p className="pl-10 text-[2em]">Experiments</p>
      </Link>

      <Link href="/threedex">
        <p className="pl-10 text-[2em]">React-three-fiber 3d model</p>
      </Link>
      {/* 
      <Link href="/physics">
        <p className="pl-10 text-[2em]">3d physics</p>
      </Link> */}
      {/* <Link href="/cursorE">
        <p className="pl-10 text-[2em]">Cursor experiment</p>
      </Link> */}
    </div>
  );
}
